sudo: required

language: go

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_HOST;
    docker push hello-work-staging/worker;
    fi

script:
- make install
